server:
  port: 9090

spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/revenuegeeks?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: chen19960119
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置检测的间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      # 配置连接在池中的最大生存时间
      max-evictable-idle-time-millis: 900000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 文件上传配置
upload:
  # 文件上传目录
  path: F:/upload/images/
  # 文件访问路径前缀
  url-prefix: /upload/images/

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.seller66.admin.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  # JWT加解密使用的密钥
  secret: seller66-admin-secret
  # JWT的有效期(60*60*24*7)
  expiration: 604800
  # Token前缀
  tokenPrefix: "Bearer "
  # 存放Token的Header Key
  header: Authorization
  